import React from "react";
import Head from "next/head";
import { Animation } from "./template/Animation";
import { Refresh } from "./template/Refresh";

export default function Home() {
  const [count, setCount] = React.useState(0)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Animation key={0} />
      </main>

    </>
  );
}
